export const DINNERWARE = [
  {
    id: 1,
    name: "Luxury Dinner Set",
    description: "Handcrafted fine ceramic dinnerware",
    shortDescription: "Short Disc",
    totalRatings: 1001,
    rating: 3,
    price: 1200,
    originalPrice: 1500,
    discount: 20,
    image: require("../assets/plates/plate.png"),
    additionalImages: [
      require("../assets/gift/gift1.png"),
      require("../assets/plates/plate.png"),
      require("../assets/plant/plant1.png"),
    ],
    reviews: [
      { name: "Amit", rating: 5, comment: "Loved it! Great quality." },
      { name: "Neha", rating: 4, comment: "Nice but a little heavy." },
    ],
  },
  {
    id: 2,
    name: "Elegant Vase",
    description: "Luxury ceramic vase with gold trim",
    shortDescription: "Short Disc",
    totalRatings: 1001,
    rating: 4.3,
    price: 3500,
    originalPrice: 4500,
    discount: 22,
    image: require("../assets/gift/gift1.png"),
    additionalImages: [
      require("../assets/gift/gift1.png"),
      require("../assets/plates/plate.png"),
      require("../assets/plant/plant1.png"),
    ],
    reviews: [
      { name: "Amit", rating: 5, comment: "Loved it! Great quality." },
      { name: "Neha", rating: 4, comment: "Nice but a little heavy." },
      { name: "Amit", rating: 5, comment: "Loved it! Great quality." },
      { name: "Neha", rating: 4, comment: "Nice but a little heavy." },
      { name: "Amit", rating: 5, comment: "Loved it! Great quality." },
      { name: "Neha", rating: 4, comment: "Nice but a little heavy." },
    ],
  },
  {
    id: 3,
    name: "Tea Pot",
    description: "Premium ceramic teapot with lid",
    shortDescription: "Short Disc",
    totalRatings: 1001,
    rating: 4.3,
    price: 900,
    originalPrice: 1200,
    discount: 25,
    image: require("../assets/plant/plant1.png"),
    additionalImages: [
      require("../assets/gift/gift1.png"),
      require("../assets/plates/plate.png"),
      require("../assets/plant/plant1.png"),
    ],
    reviews: [
      { name: "Amit", rating: 5, comment: "Loved it! Great quality." },
      { name: "Neha", rating: 4, comment: "Nice but a little heavy." },
    ],
  },
  {
    id: 1,
    name: "Luxury Dinner Set",
    description: "Handcrafted fine ceramic dinnerware",
    shortDescription: "Short Disc",
    totalRatings: 1001,
    rating: 4.3,
    price: 1200,
    originalPrice: 1500,
    discount: 20,
    image: require("../assets/plates/plate.png"),
    additionalImages: [
      require("../assets/gift/gift1.png"),
      require("../assets/plates/plate.png"),
      require("../assets/plant/plant1.png"),
    ],
    reviews: [
      { name: "Amit", rating: 5, comment: "Loved it! Great quality." },
      { name: "Neha", rating: 4, comment: "Nice but a little heavy." },
    ],
  },
  {
    id: 2,
    name: "Elegant Vase",
    description: "Luxury ceramic vase with gold trim",
    shortDescription: "Short Disc",
    totalRatings: 1001,
    rating: 4.3,
    price: 3500,
    originalPrice: 4500,
    discount: 22,
    image: require("../assets/gift/gift1.png"),
    additionalImages: [
      require("../assets/gift/gift1.png"),
      require("../assets/plates/plate.png"),
      require("../assets/plant/plant1.png"),
    ],
    reviews: [
      { name: "Amit", rating: 5, comment: "Loved it! Great quality." },
      { name: "Neha", rating: 4, comment: "Nice but a little heavy." },
    ],
  },
  {
    id: 3,
    name: "Tea Pot",
    description: "Premium ceramic teapot with lid",
    shortDescription: "Short Disc",
    totalRatings: 1001,
    rating: 4.3,
    price: 900,
    originalPrice: 1200,
    discount: 25,
    image: require("../assets/plant/plant1.png"),
    additionalImages: [
      require("../assets/gift/gift1.png"),
      require("../assets/plates/plate.png"),
      require("../assets/plant/plant1.png"),
    ],
    reviews: [
      { name: "Amit", rating: 5, comment: "Loved it! Great quality." },
      { name: "Neha", rating: 4, comment: "Nice but a little heavy." },
    ],
  },
  {
    id: 1,
    name: "Luxury Dinner Set",
    description: "Handcrafted fine ceramic dinnerware",
    shortDescription: "Short Disc",
    totalRatings: 1001,
    rating: 4.3,
    price: 1200,
    originalPrice: 1500,
    discount: 20,
    image: require("../assets/plates/plate.png"),
    additionalImages: [
      require("../assets/gift/gift1.png"),
      require("../assets/plates/plate.png"),
      require("../assets/plant/plant1.png"),
    ],
    reviews: [
      { name: "Amit", rating: 5, comment: "Loved it! Great quality." },
      { name: "Neha", rating: 4, comment: "Nice but a little heavy." },
    ],
  },
  {
    id: 2,
    name: "Elegant Vase",
    description: "Luxury ceramic vase with gold trim",
    shortDescription: "Short Disc",
    totalRatings: 1001,
    rating: 4.3,
    price: 3500,
    originalPrice: 4500,
    discount: 22,
    image: require("../assets/gift/gift1.png"),
    additionalImages: [
      require("../assets/gift/gift1.png"),
      require("../assets/plates/plate.png"),
      require("../assets/plant/plant1.png"),
    ],
    reviews: [
      { name: "Amit", rating: 5, comment: "Loved it! Great quality." },
      { name: "Neha", rating: 4, comment: "Nice but a little heavy." },
    ],
  },
  {
    id: 3,
    name: "Tea Pot",
    description: "Premium ceramic teapot with lid",
    shortDescription: "Short Disc",
    totalRatings: 1001,
    rating: 4.3,
    price: 900,
    originalPrice: 1200,
    discount: 25,
    image: require("../assets/plant/plant1.png"),
    additionalImages: [
      require("../assets/gift/gift1.png"),
      require("../assets/plates/plate.png"),
      require("../assets/plant/plant1.png"),
    ],
    reviews: [
      { name: "Amit", rating: 5, comment: "Loved it! Great quality." },
      { name: "Neha", rating: 4, comment: "Nice but a little heavy." },
    ],
  },
];
